spring:
  datasource:
    url: ${DATASOURCE_URL_PROD}
    username: ${DATASOURCE_USERNAME_PROD}
    password: ${DATASOURCE_PASSWORD_PROD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: none

  session:
    store-type: jdbc
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
      table-name: SPRING_SESSION
      initialize-schema: always

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

image:
  resource:
    location: ${IMAGE_RESOURCE_LOCATION}
  path: ${IMAGE_PATH}




