spring:
  datasource:
    url: ${datasource_url}
    username: ${datasource_username}
    password: ${datasource_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    store-type: redis

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: none

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth_client_id}
            client-secret: ${oauth_client_secret}
            scope:
              - profile
              - email

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${mail_username}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: smtp.gmail.com

  redis:
    host: ${redis_host}
    port: ${redis_port}


cloud:
  aws:
    credentials:
      access-key: ${aws_access_key}
      secret-key: ${aws_secret_key}
    s3:
      bucket: ${aws_s3_bucket}
    stack:
      auto: false
    endpoint: ${aws_endpoint}