spring:
  datasource:
    url: ${DATASOURCE_URL_PROD}
    username: ${DATASOURCE_USERNAME_PROD}
    password: ${DATASOURCE_PASSWORD_PROD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    store-type: jdbc

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: none

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_CLIENT_ID_PROD}
            client-secret: ${OAUTH_CLIENT_SECRET_PROD}
            scope:
              - profile
              - email

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USERNAME_PROD}
    password: ${MAIL_PASSWORD_PROD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: smtp.gmail.com

  redis:
    host: ${REDIS_HOST_PROD}
    port: ${REDIS_PORT_PROD}
